# important: never change version manually
# it is used by `quokka upgrade` command
VERSION: 1.0.0

# App reads values provided under `QUOKKA` namespace.
# settings can be lower or upper case does not matter
# as internally Dynaconf transform to upper case.
QUOKKA:

  # Enable login for admin access
  ADMIN_REQUIRES_LOGIN: false

  # Enable login for website
  WEBSITE_REQUIRES_LOGIN: false

  # DEBUG Mode
  DEBUG: true
  DEBUG_TOOLBAR_ENABLED: true
  ADMIN_RAISE_ON_VIEW_EXCEPTION: true
  LOGGER_ENABLED: True

  # Secret Key must be in .secrets.yml ir QUOKKA_SECRET_KEY env var.
  # SECRET_KEY: abcderf

  WTF_CSRF_ENABLED: true

  # be careful touching this list, use EXTRA_EXTENSIONS for custom extensions
  CORE_EXTENSIONS:
    - quokka.core.babel.configure
    - quokka.admin.configure_admin
    - flask_wtf.csrf.CSRFProtect
    - quokka.core.gravatar.configure
    - flask_mistune.Mistune
    - quokka.core.security.configure
    - quokka.core.error_handlers.configure
    - quokka.core.monitoring.configure
    - quokka.core.themes.configure
    - quokka.core.content.configure
    - quokka.admin.configure_file_admin
    - quokka.admin.configure_extra_views
    - quokka.core.security.configure_user_admin

  # Extensions here can be import path to any callable or class
  # that callable will receive objects app, db and admin.
  # example:
  # def configure_my_extension(app, db, admin):
  #    load_extension_here
  # publish your extension to python path `pip isntall quokka_extension`
  # add to the list `- quokka_extension.module.configure_my_extension`
  EXTRA_EXTENSIONS: []
    # - quokka.core.test.configure

  CONTENT_TYPES:
    markdown:
      choice_text: Markdown
      help_text: Markdown text editor
      content_type_class: quokka.core.content_types.MarkdownContentType
    html:
      choice_text: HTML
      help_text: Rich HTML text editor
      content_type_class: quokka.core.content_types.HTMLContentType
    plaintext:
      choice_text: Plain Text
      help_text: Pure plain text in text area
      content_type_class: quokka.core.content_types.PlainContentType

  # if true any package named quokka_ will be loaded
  AUTO_LOAD_EXTENSIONS: true
  # else provide a list
  # Plugin settings might be namespaced in dynaconf

  # TinyDB
  db_system: tinydb
  db_folder: databases
  # Mongo
  # db_system: mongo
  # db_name: quokka_db
  # db_username: admin
  # db_password: secret
  # db_host: myhost.com
  # db_port: 27017

  # db and collection names
  # for pymongo you can have
  # all db_ poiting to the same db
  db_index: index
  db_contents: contents
  db_uploads: uploads
  db_users: users

  collection_index: index
  collection_contents: contents
  collection_uploads: uploads
  collection_users: users

  # Flask-Gravatar can take avatar urls in jinja templates
  # do: {{ current_user.email | gravatar }} or
  # {{ 'some@server.com' | gravatar(size=50) }}
  GRAVATAR:
    size: 100
    rating: g
    default: retro
    force_default: false
    force_lower: false

  DEFAULT_TEXT_FORMAT: markdown

  ADMIN:
    name: Quokka NG Admin
    url: /admin

  FLASK_ADMIN_SWATCH: default
  FLASK_ADMIN_TEMPLATE_MODE: bootstrap3


  # ADMIN_ICONS: [
  #     ['post.create_view', 'pencil', 'Write'],
  #     ['post.index_view', 'th-list', 'Posts'],
  #     ['config.index_view', 'cog', 'Config'],
  #     ['user.index_view', 'user', 'Users'],
  #     ['image.index_view', 'picture', 'Images'],
  #     ['image.create_view', 'arrow-up', 'Upload'],
  #     ['channel.index_view', 'th-list', 'Channels']
  # ]

  DEFAULT_EDITABLE_EXTENSIONS: &extensions [
    'html', 'css', 'js', 'py', 'txt', 'md', 'cfg', 'coffee', 'html', 'json',
    'xml', 'yaml', 'yml', 'HTML', 'CSS', 'JS', 'PY', 'TXT', 'MD', 'CFG',
    'COFFEE', 'HTML', 'JSON', 'XML', 'YAML', 'YML'
  ]

  FILE_ADMIN:
    - name: Themes
      category: Files
      path: themes
      url: /themesfiles/  # create nginx rule
      endpoint: themes_files
      editable_extensions: *extensions
    - name: Uploads
      category: Files
      path: uploads
      url: /uploadsfiles/  # Create nginx rule
      endpoint: uploads_files
      editable_extensions: *extensions
    - name: Databases
      category: Files
      path: databases
      url: /databasesfiles/  # Create nginx rule
      endpoint: databases_files
      editable_extensions: *extensions

  # All this languages will be available to translate admin panel
  # and also as language to post content
  BABEL_LANGUAGES: &languages [
      'en', 'cs', 'de', 'es', 'fa', 'fr', 'pt', 'ru', 'pa', 'zh_CN', 'zh_TW'
  ]
  # this will be the default language on admin and front end
  # admin language can also be user based
  BABEL_DEFAULT_LOCALE: &default_locale pt

  # Home page and categories lists all content on this languages no filter
  # should be a list e.g: ['en'] to filter only english by default
  # anyway accessing site.com/LANG/ would filter specific language
  # static site generation loops on *languages
  # translations variable list all translations urls in theme
  FILTER_LANGUAGES: *languages

  LOGGER_LEVEL: DEBUG
  LOGGER_FORMAT: '%(asctime)s %(name)-12s %(levelname)-8s %(message)s'
  LOGGER_DATE_FORMAT: '%d.%m %H:%M:%S'

  DEBUG_TB_INTERCEPT_REDIRECTS: false
  DEBUG_TB_PROFILER_ENABLED: true
  DEBUG_TB_TEMPLATE_EDITOR_ENABLED: true
  DEBUG_TB_PANELS:
    - flask_debugtoolbar.panels.versions.VersionDebugPanel
    - flask_debugtoolbar.panels.timer.TimerDebugPanel
    - flask_debugtoolbar.panels.headers.HeaderDebugPanel
    - flask_debugtoolbar.panels.request_vars.RequestVarsDebugPanel
    - flask_debugtoolbar.panels.template.TemplateDebugPanel
    # TODO: MIgrate mongoengine panel to tinyDB and Pymongo
    # - flask_mongoengine.panels.MongoDebugPanel
    - flask_debugtoolbar.panels.logger.LoggingPanel
    - flask_debugtoolbar.panels.profiler.ProfilerDebugPanel
    - flask_debugtoolbar.panels.config_vars.ConfigVarsDebugPanel

  DEFAULT_THEME: Flex
  # https://github.com/alexandrevicenzi/Flex
  # https://github.com/alexandrevicenzi/Flex/wiki/Custom-Settings
  # http://www.pelicanthemes.com/
  # $ quokka themes install theme-name
  # $ quokka themes activate theme-name
  # http://docs.getpelican.com/en/latest/themes.html

  THEME_PATHS: themes
  # content urls will end with .html
  CONTENT_EXTENSION: html

  # monitoring
  # You must install `raven` package to use it
  SENTRY_ENABLED: false
  # Sentry DSN Key must be in .secrets.yml or QUOKKA_SENTRY_DSN env var.
  # SENTRY_DSN: ''

  # https://opbeat.com is application monitoring tool
  # you can enable it but you need to install opbeat
  # https://opbeat.com/docs/articles/get-started-with-flask/

  # OPBEAT must be in .secrets.yml or QUOKKA_OPBEAT='@json {..}' env var.
  # you must install `opbeat` package to use it
  # OPBEAT:
  #   ORGANIZATION_ID: '<ORGANIZATION-ID>'
  #   APP_ID: '<APP-ID>'
  #   SECRET_TOKEN: '<SECRET-TOKEN>'
  #   INCLUDE_PATHS: ['quokka']
  #   DEBUG: true
  #   LOGGING': False
