language: python
python:
  - "2.7"
  - "3.4"
services: mongodb
install:
  - "pip install --upgrade -r requirements/requirements.txt"
  - "pip install --upgrade -r requirements/test.txt"
script: make test
after_success:
  - coveralls
notifications:
  slack: quokkaproject:pjF8y81mqwXxQRtf5sGz5zqr
